"""
False Failure Detection Test

This test ensures that QC validation errors correspond to actual data issues
and are not false positives generated by incorrect validation logic.

Critical for:
- Post-deployment validation
- After rule updates or engine changes
- Regression testing for cross-form validation
- Ensuring data quality reliability

Test Strategy:
1. Load most recent QC validation errors
2. Cross-validate against source data
3. Verify error values match actual data
4. Validate cross-form compatibility rules
5. Flag any false positives

Expected Results:
- False positive rate: < 2% (excellent) or < 5% (acceptable)
- All errors should correspond to actual data issues
- Cross-form rules should be internally consistent
"""

import re
from pathlib import Path
from typing import Dict, Tuple

import pandas as pd
import pytest


class TestFalseFailures:
    """Test suite for detecting false positive validation errors."""

    @pytest.fixture(scope="class")
    def latest_validation_data(self) -> Tuple[pd.DataFrame, pd.DataFrame, Path]:
        """Load the most recent validation output and source data."""
        output_dir = Path("output")
        output_dirs = sorted(
            [d for d in output_dir.iterdir() if d.is_dir()],
            key=lambda x: x.stat().st_mtime,
            reverse=True,
        )

        if not output_dirs:
            pytest.skip("No output directories found - run QC validation first")

        latest_dir = output_dirs[0]

        # Load errors
        error_csv = list((latest_dir / "Errors").glob("Final_Error_Dataset_*.csv"))
        if not error_csv:
            pytest.skip(f"No error CSV found in {latest_dir}")
        errors_df = pd.read_csv(error_csv[0])

        # Load source data
        data_dir = latest_dir / "Data_Fetched"
        report_data = list(data_dir.glob("Report_Data_*.csv"))
        if not report_data:
            pytest.skip(f"No source data found in {data_dir}")
        data_df = pd.read_csv(report_data[0])

        return errors_df, data_df, latest_dir

    def _validate_error_against_data(
        self, error_row: pd.Series, data_df: pd.DataFrame
    ) -> Dict[str, any]:
        """
        Validate a single error against source data.

        Returns:
            dict with 'status' ('valid', 'false_positive', 'data_missing', 'complex')
            and 'reason' explaining the result.
        """
        ptid = error_row["ptid"]
        variable = error_row["variable"].lower()
        error_msg = error_row["error_message"]
        current_value = error_row["current_value"]

        # Find matching record
        matching_records = data_df[data_df["ptid"] == ptid]
        if len(matching_records) == 0:
            return {"status": "data_missing", "reason": "No matching record in source data"}

        record = matching_records.iloc[0]

        # Normalize column names
        data_cols = {col.lower(): col for col in data_df.columns}
        actual_col = data_cols.get(variable)

        # Cross-form validation (variable might be in different instrument)
        if actual_col is None:
            if "compatibility rule" in error_msg.lower():
                return {
                    "status": "complex",
                    "reason": "Cross-form validation - requires multi-field check",
                }
            return {"status": "data_missing", "reason": f"Variable {variable} not in data columns"}

        # Get actual value from data
        actual_value = record[actual_col]
        if pd.isna(actual_value):
            actual_value = ""
        else:
            actual_value = str(actual_value)

        # Normalize current_value from error
        if pd.isna(current_value):
            current_value = ""
        else:
            current_value = str(current_value)

        # Validate based on error type
        if "null value not allowed" in error_msg:
            if actual_value == "":
                return {"status": "valid", "reason": "Required field is empty"}
            else:
                return {
                    "status": "false_positive",
                    "reason": f'Error says null but data has "{actual_value}"',
                }

        elif "unallowed value" in error_msg.lower():
            # Extract unallowed value from message
            match = re.search(r"unallowed value ([^\]'\"]+)", error_msg)
            if match:
                error_value = match.group(1).strip("'\"").strip()
                actual_clean = actual_value.strip()

                # Normalize float comparisons
                try:
                    if "." in actual_clean:
                        values_match = float(actual_clean) == float(error_value)
                    else:
                        values_match = actual_clean == error_value
                except (ValueError, TypeError):
                    values_match = actual_clean == error_value

                if values_match:
                    return {
                        "status": "valid",
                        "reason": f"Data contains unallowed value {actual_value}",
                    }
                else:
                    return {
                        "status": "false_positive",
                        "reason": f'Error says "{error_value}" but data has "{actual_value}"',
                    }

        elif "must be blank" in error_msg.lower() or "must be empty" in error_msg.lower():
            if actual_value != "":
                return {"status": "valid", "reason": "Field should be blank but has value"}
            else:
                return {
                    "status": "false_positive",
                    "reason": "Error says not blank but value is empty",
                }

        elif "compatibility rule" in error_msg.lower():
            return {
                "status": "complex",
                "reason": "Cross-form compatibility rule - requires multi-field validation",
            }

        # Default: assume valid if value matches
        values_match = (
            actual_value == current_value
            or (actual_value == "" and current_value in ["nan", "NaN", ""])
            or (actual_value == "nan" and current_value == "")
        )

        if values_match:
            return {"status": "valid", "reason": "Value matches error description"}
        else:
            return {
                "status": "false_positive",
                "reason": f'Mismatch: error says "{current_value}", data has "{actual_value}"',
            }

    def test_no_false_positives(self, latest_validation_data):
        """
        Verify that validation errors are legitimate and not false positives.

        Acceptance criteria:
        - False positive rate < 5% (acceptable)
        - False positive rate < 2% (excellent)
        - All detected false positives should be investigated
        """
        errors_df, data_df, latest_dir = latest_validation_data

        results = {"valid": [], "false_positive": [], "data_missing": [], "complex": []}

        # Validate each error
        for idx, error in errors_df.iterrows():
            validation = self._validate_error_against_data(error, data_df)
            results[validation["status"]].append(
                {
                    "ptid": error["ptid"],
                    "variable": error["variable"],
                    "error": error["error_message"][:80],
                    "reason": validation["reason"],
                }
            )

        # Calculate statistics
        total = len(errors_df)
        valid_count = len(results["valid"])
        false_positive_count = len(results["false_positive"])
        complex_count = len(results["complex"])

        false_positive_rate = (false_positive_count / total * 100) if total > 0 else 0

        # Generate detailed report
        report_lines = [
            f"\n{'=' * 80}",
            "FALSE FAILURE DETECTION TEST",
            f"{'=' * 80}",
            f"Dataset: {latest_dir.name}",
            "",
            "VALIDATION BREAKDOWN:",
            f"  Total errors analyzed:    {total:>6,}",
            f"  Validated as real:        {valid_count:>6,}",
            f"  Complex rules (cross):    {complex_count:>6,}",
            f"  FALSE POSITIVES:          {false_positive_count:>6,}",
            f"  Data not found:           {len(results['data_missing']):>6,}",
            "",
            f"FALSE POSITIVE RATE: {false_positive_rate:.2f}%",
            "",
        ]

        if false_positive_count > 0:
            report_lines.append("FALSE POSITIVES DETECTED:")
            report_lines.append("-" * 80)
            for fp in results["false_positive"][:10]:
                report_lines.append(f"  PTID: {fp['ptid']} | Variable: {fp['variable']}")
                report_lines.append(f"    Error: {fp['error']}")
                report_lines.append(f"    Reason: {fp['reason']}")
                report_lines.append("")
            if false_positive_count > 10:
                report_lines.append(f"  ... and {false_positive_count - 10} more")

        report = "\n".join(report_lines)
        print(report)

        # Assert based on thresholds
        assert false_positive_rate < 5.0, (
            f"CRITICAL: False positive rate {false_positive_rate:.2f}% exceeds 5% threshold.\n"
            f"{false_positive_count} false positives detected out of {total} errors.\n"
            f"Validation logic requires investigation.\n"
            f"{report}"
        )

        if false_positive_rate >= 2.0:
            pytest.warns(
                UserWarning,
                match=(
                    f"False positive rate {false_positive_rate:.2f}% "
                    "is acceptable but should be reviewed"
                ),
            )

    def test_cross_form_consistency(self, latest_validation_data):
        """
        Verify cross-form compatibility rules are internally consistent.

        Samples a subset of cross-form errors and validates that both
        trigger and target variables can be found in the data.
        """
        errors_df, data_df, latest_dir = latest_validation_data

        cross_form_errors = errors_df[
            errors_df["error_message"].str.contains("compatibility rule", case=False, na=False)
        ]

        if len(cross_form_errors) == 0:
            pytest.skip("No cross-form errors to validate")

        sample_size = min(20, len(cross_form_errors))
        sample_errors = cross_form_errors.sample(n=sample_size, random_state=42)

        inconsistencies = []

        for idx, error in sample_errors.iterrows():
            ptid = error["ptid"]
            error_msg = error["error_message"]

            # Extract trigger and target variables
            trigger_match = re.search(r"for if \{'([^']+)':", error_msg)
            target_match = re.search(r"^\('([^']+)',", error_msg)

            if trigger_match and target_match:
                trigger_var = trigger_match.group(1)
                target_var = target_match.group(1)

                record = data_df[data_df["ptid"] == ptid]
                if len(record) > 0:
                    record = record.iloc[0]
                    data_cols = {col.lower(): col for col in data_df.columns}

                    trigger_col = data_cols.get(trigger_var.lower())
                    target_col = data_cols.get(target_var.lower())

                    if trigger_col is None or target_col is None:
                        inconsistencies.append(
                            {
                                "ptid": ptid,
                                "trigger": trigger_var,
                                "target": target_var,
                                "issue": (
                                    f"Missing column: trigger={trigger_col}, target={target_col}"
                                ),
                            }
                        )

        assert len(inconsistencies) == 0, (
            f"Found {len(inconsistencies)} cross-form inconsistencies:\n"
            + "\n".join(
                [
                    f"  PTID {i['ptid']}: {i['trigger']} -> {i['target']} | {i['issue']}"
                    for i in inconsistencies
                ]
            )
        )

    def test_error_dataset_completeness(self, latest_validation_data):
        """
        Verify error dataset has all required fields.

        Ensures the error output format is complete and consistent.
        """
        errors_df, _, _ = latest_validation_data

        required_columns = [
            "ptid",
            "variable",
            "error_message",
            "current_value",
            "instrument_name",
            "nacc_check_code",  # Changed from 'check_code' to match actual schema
        ]

        missing_columns = [col for col in required_columns if col not in errors_df.columns]

        assert len(missing_columns) == 0, (
            f"Error dataset missing required columns: {missing_columns}"
        )

        # Check for null values in critical columns
        critical_nulls = {}
        for col in ["ptid", "variable", "error_message"]:
            null_count = errors_df[col].isna().sum()
            if null_count > 0:
                critical_nulls[col] = null_count

        assert len(critical_nulls) == 0, f"Critical columns have null values: {critical_nulls}"
